### ISSUE TITLE
Remove overkill instruction

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/ember-object-diagnostic#102]
We needed something to make it clear they are to work in `diagnostic.js`, but this is too much.
Please remove.
```diff
- 1.  Do not work inside the actual ember app in this repository.
```

**Comment by BenGitsCode** [comment]
@jrhorn424 had me add this explicitly.

**Comment by jrhorn424** [comment]
I'm happy to re-open if @raq929 has a compelling reason.
